### ISSUE TITLE
When genes are already loaded, clicking on ACMG genes button causes all genes to disappear.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#370] opened 2016-07-22 06:20 UTC

**Comment by AlistairNWard** [comment] 2016-07-22 11:38
This was actually by design to avoid having millions of open genes. Gets back to a previous discussion about what genes to show when multiple methods are used. If I have 20 genes open, then click ACMG56, I'll have 76 and won't necessarily know which ones are ACMG56, especially if sorting the genes. Same goes for selecting a gene panel (once we implement them). I think we need to reopen the discussion on having 'sets' of genes. If I'm looking at 10 genes, this constitutes a set. Then if I select ACMG56, those are a second set. I could choose to view only one of the sets, or a union etc.

**Comment by AlistairNWard** [comment] 2016-08-02 17:07
I'll close this, since by the title of the issue, it is fixed. Issue #380 opened to work on this.

**Closed** 2016-08-02 17:08 UTC
