### ISSUE TITLE
Tooltip scrolling behavior

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#705] opened 2017-09-19 15:33 UTC
Is it possible to have it scroll with the window, but when the top of the tooltip reaches the top of the screen, it no longer scrolls with the page. I feel like I've seen this behaviour before. BUT, this is hardly top of the list of things to deal with.

**Comment by AlistairNWard** [comment] 2017-09-19 17:53
Duplicate of #678.

**Closed by AlistairNWard** 2017-09-19 17:53 UTC
