### ISSUE TITLE
Automatically close tooltip when changing gene

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#704] opened 2017-09-18 13:02 UTC
If I click on a variant and open the tooltip, then change gene, the tooltip remains open. Since this variant is no longer available in this gene, it makes sense to automatically close the tooltip.

**Comment by tonydisera** [comment] 2017-10-16 20:48
duplicate of #728

**Closed** 2017-10-16 20:48 UTC
