### ISSUE TITLE
Filtering on AF problems

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#496] opened 2016-11-17 02:25 UTC
1. Change 1-5% to < 5%
2. Boxes for setting custom range is missing.

**Comment by tonydisera** [comment] 2016-11-17 04:14
This was by design.  I thought it would be confusing to specify both a predefined range (<5%) and and a custom range (1-5%).  So when a custom range is entered, the user shouldn't be able to specify a predefined range and vice versa.  However, I notice that you can in fact enter both a predefined range and a custom range if the range is entered first and then the pre-defined range is selected.  
Once we have the legend, I think it would be easier if we just got rid of the predefined ranges and just had the text boxes for defining a range.

**Comment by AlistairNWard** [comment] 2016-11-17 12:49
1. Ah. So the custom range is always available now, so that's good!

2. I was suggesting that we remove the 1-5% predefined range, and replace it with <5%. Typically, people are interested in finding variants with lower than a particular AF, so it's probably unlikely to want a lower bound set as a standard filter.

3. We could get rid of all the predefined ranges, that's probably not a bad idea. I was thinking that if you set a custom range, it would deselect any of the predefined values, but maybe just a custom range is sufficient, and then cleans up the panel a bit.

**Comment by tonydisera** [comment] 2017-10-17 00:46
Addressed in gene 2.5 by consolidating AF filters into on range check.

**Closed by tonydisera** 2017-10-17 00:46 UTC
Labels: ready
