### ISSUE TITLE
On nv-dev 2.3 the gene suggestion drop down doesn't pop to front

### ISSUE THREAD

**Issue by mvelinder** [tonydisera/gene.iobio#592] opened 2017-04-11 15:53 UTC
![image](https://cloud.githubusercontent.com/assets/22081541/24918194/c575e266-1e9c-11e7-8f4f-3d175a2090a9.png)

**Comment by AlistairNWard** [comment] 2017-04-11 15:57
Duplicate of #593.

**Closed by AlistairNWard** 2017-04-11 15:57 UTC
