### ISSUE TITLE
Variants not found

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#152] opened 2015-11-14 15:40 UTC
Intermittent issue. Sometimes when data is loaded in, some of the panels come up with the warning that no variants are found - even though there are variants in the gene for the sample. Hitting refresh will sometimes fix the problem, but sometimes a different sample will show no variants.

Tough to fix, since I can't find a way to reliably reproduce the error, but we need to prioritize this.

**Comment by tonydisera** [comment] 2015-11-19 20:06
I'm seeing this problem frequently today.  In this case, all the services are 'healthy'.  It appears to be a problem with the connection between the snpEff client and server.  Here's the error:

     vep Error: snpEff Error: stderr - events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect EHOSTUNREACH
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
vcf.iobio.js:715 vep Error: snpEff Error: stderr - 

vcf.iobio.js:715 vep Error: snpEff Error: prog process exited with code 1
app.js:963 problem caching data for gene PALB2. problem when getting variants - null set returned.

**Comment by tonydisera** [comment] 2016-01-04 02:21
Yi and I have been dealing with this issue.  
From Yi:
snpeff-backend is the java app backend. I suspect that it crashes and gets restarted without restarting the light iobio service (snpeff), causing the later to no longer be able to communicate with the former. If you start them altogether, the system knows to start snpeff-backend first

**Comment by tonydisera** [comment] 2016-01-04 02:24
I'm not sure if there is an easy fix for this issue.  Now that vep no longer runs with the HGVS flag turned on, vep zombie processes are probably not the cause of the backend issues.  To address the snpEff backend issue we will have to either address the snpEff failure (difficult as this is probably a out-of-heap-space issue) or figure out how to restart the snpeff service along with the snpeff backend service.

**Comment by tonydisera** [comment] 2016-02-25 23:34
I've spent a few day trying to narrow down what is going on.  Yi has been helping me troubleshoot.  Here's what we know so far:
1. I can consistently reproduce this problem with just tabix + a service that cats the stdin, about every 30-70 iterations that involve 3 simultaneous curls.  We see a truncation of vcf records (e.g. 89 out of 174, 172 out of 174).  The nth vcf record is typically truncated in the middle.  

2. The problem doesn't seem to occur when we are just curling tabix.  This could be because it is a websocket issue.  (Is there a way to force all iobio services through http?)

3. We can rule out the annotation services like snpeff and vep as being the culprits; however the problem seems to manifest into 0 records when the truncated vcf record set goes through vt subset.  The error occurs on file open. 

4. The more services that are added into a URL, the more frequently we see the problem (every 20 iterations for full URL) .

5. The problem occurs on nv-blue as well as production,, so it must not be an elastic load balancer issue.

**Comment by tonydisera** [comment] 2016-03-08 18:42
Chewy prevailed!!!! 
Culprit: output stream does not need to be closed manually
Since the program's stdout is piped to output stream, nodejs will
properly handle the closing of the stream when data in stdout pipe is
consumed. Capturing either the 'close', or the 'exit' event of the
running program, and close stream manually, will cause the stream to be
closed too early while data still sits in Linux pipe buffer, especially
under heavy load, and causes truncation to occur.

You can view, comment on, or merge this pull request online at:

  https://github.com/iobio/minion/pull/13

Commit Summary

Fixed the truncation bug that long haunted us
File Changes

M lib/cmd.js (6)
Patch Links:

https://github.com/iobio/minion/pull/13.patch
https://github.com/iobio/minion/pull/13.diff
—

**Closed by tonydisera** 2016-03-08 18:42 UTC
Labels: bug, high priority, wait for next release?
