### ISSUE TITLE
Freebayes variants don't refresh when color scheme (from impact to effect) changes.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#22] opened 2015-04-28 23:41 UTC
[This may have been fixed.  Please validate.]

**Comment by AlistairNWard** [comment] 2016-03-15 14:24
I just tested this and it actually seems to be a different problem now. Open gene, open the demo exome data set, go to TTN, call variants. There should be 1 variant called in each member of the trio. Change colour scheme from Impact to Effect and the called variants disappear totally. Returning to Impact does not reinstate the variants!

The problem is related to the filter status. When we call the variants with Freebayes, there is no filtering and so the filter status is set to '.'. If we have defaulted to PASS, as we have in this case, they should not be displayed. They are on initial calling, but then as we modify filters, they disappear unless we choose to show '.' variants. We should simply make called variants not subject to the filter status filtering.

**Comment by AlistairNWard** [comment] 2016-11-01 12:49
This no longer occurs, so has probably been fixed in all the recent improvements.

**Closed by AlistairNWard** 2016-11-01 12:49 UTC
